 import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
// import { Inter } from "next/font/google";
import { type Metadata } from "next";

// const inter = Inter({
//   variable: "--font-sans"
// })

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav(){
  return (
    <nav className="flex w-full items-center justify-between p-4 border text-xl font-semibold">
      <div className="">E Gallery</div>
      <div className="">Sign In</div>

    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`font-sans  flex flex-col gap-4`}>
      <TopNav/>

        {children}
        </body>
    </html>
  );
}
