 import "~/styles/globals.css";
 import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import { GeistSans } from "geist/font/sans";
// import { Inter } from "next/font/google";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";

// const inter = Inter({
//   variable: "--font-sans"
// })

export const metadata: Metadata = {
  title: "E Gallery",
  description: "Generated by Elise Oyi",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`font-sans  flex flex-col gap-4`}>
      <TopNav/>

        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
